# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Service Desk Site 
email: servicedesk@digital.justice.gov.uk
description: > # this means to ignore newlines until "baseurl:"
  The Digital Service Desk, providing  quality service for our digital teams...
  Phone us on 0203 334 6096
  HipChat us via the Digital Service Desk room
  Visit us at Post Point 11.55
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
